const ip = 'api.esukh.mn'//43.231.113.13 
const config = {
  advertiseImgPath: 'http://' + ip + '/api/v1/files/advertiseimg/',
  branchImgPath: 'https://' + ip + '/api/v1/files/branchimg/',
  branchLogoPath: 'https://' + ip + '/api/v1/files/branchlogo/',
  workerImgPath: 'https://' + ip + '/api/v1/files/workerimg/',
  workerFilePath: 'https://' + ip + '/api/v1/files/workerfile/',
  userImgPath: 'https://' + ip + '/api/v1/files/userimg/',
  infoImgPath: 'https://' + ip + '/api/v1/files/infoimg/',
  infoFilePath: 'https://' + ip + '/api/v1/files/file/',
  commentImgPath: 'https://' + ip + '/api/v1/files/commentimg/',
  capitalImgPath: 'https://' + ip + '/api/v1/files/capitalimg/',
  complainImgPath: 'https://' + ip + '/api/v1/files/complainimg/',
  complainFilePath: 'https://' + ip + '/api/v1/files/complainfile/',
  forumImgPath: 'https://' + ip + '/api/v1/files/forumimg/',
  forumFilePath: 'https://' + ip + '/api/v1/files/forumfile/',
  pollImgPath: 'https://' + ip + '/api/v1/files/pollimg/',
  pollFilePath: 'https://' + ip + '/api/v1/files/pollfile/',
  roomImgPath: 'https://' + ip + '/api/v1/files/roomimg/',
  url: 'https://' + ip + '/api/v1',
  filePath: 'https://' + ip + '/api/v1/files/file/',
  examplefilePath: 'https://' + ip + '/api/v1/files/examplefile/',
  propertyTypes: ['', 'сууц', 'граж', 'агуулах'],
  paymentBranchType: ['ШИЛЭН СӨХ', 'САЙН СӨХ', 'СУПЕР СӨХ'],
  stageTypes: ['Шинэ', 'Хүлээн авсан', 'Хариу оруулсан','Хаагдсан'],
  complainTypes: ['Санал', 'Гомдол', 'Дуудлага'],
  ownerTypes: ['Өмчлөгч', 'Хамтран өмчлөгч', 'Түрээслэгч','Бусад'],
  dateFormat:'YYYY/MM/DD',
  dateTimeFormat:'YYYY/MM/DD HH:MM',
  carLogo:`iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAACXBIWXMAAAsTAAALEwEAmpwYAAADHUlEQVR4nO2YS0iUURiGnywqLdA21SLohi0sSDCDSKtFi4wuVEbURoOiK0GQVNBWKmrVBdq1smhTEVQqtSgJCrogpOLCktK8FLoKxxib+OAdOA3jXP9/mup/4ducy/t+75xzvnPmhwABAgQIECBAgH8Gi4GDwFXgFtAKvAbagR6gFxgBRoGIYlRtvRrTrjkt4rgiTuPOCfYAY06CXscYsNtvEyuAkATvAickuhFYBZQDS4BFwBygxJlboraFGrMSqAQ2A/XAWeCeY2a5XyamAm8kdM0vEeCGNGzbFfghsE8CH4Ai/MMs4KO09npNbr9Ml8jtQPqNQ9Lq9HpVtoh4EJiJ/5gBfJGmnaGMYYf3PjAM3FSJNNLT5A5npNmiHIaVk+WWMqLbKB+jKx0jbcDPGIIHQHcOE+6WpttmOT1Pe22BWiAMTABlugdac2CiWfdOmbTDyiUjbAfGRfwDqHMOYrOPJh4D06VVJ+2IctmWrok1jgk3Tqm/SEvstYlnzh3VEKc/pNxSwmygbxIh26PHNK4Y6PDQhHEZp+F4gnF9ujST4oBzGZUCS4GnDpHt2R0aa2+mrx6YGBaXYac0on1P1FfqVNP9pIA7GrzLaZumpR5Q33egQn1VzkMyk7C51eKqEHdEWg3SjqJWfbdTMdKpwXPj9NlBv6D+fmCB8ysOZmBiwFld4+pX+3lpxWKe+t+nYuSbBh/VclrJnaI3z3wtazSRd86+zgZWat86vPXSKpC25bBM5zO6FZNiPINDuhUozMBAoUpqVwbbMSnCHlYivyKc3MbvFSNfYyIVI5G/JJIi0WSrTC+Bc6rtGzxMbL04jftVClUwbSOJsNZDI8meHlkbKY6p4/bl4/AkT/1swrja9De3Ulpuec7aiH3mMTz6A+fgobRXe2HkotrLJ/kVL2f5ddBeEEecp0nECdM0XPLCSPTpXB2n7yTeYV2cN1uVtENeGMnXSIr/xkgjcB1o0mF8ofdWj2JIX91HYrZEyGkfcsZ3iMO4msTdmAsjuUIk2zw+J5j8yf/8vcujRgPjTd5E7lCTJ3kECBCAPMIvd+NjCRRHhhcAAAAASUVORK5CYII=`
}
export default config
